[package]
name = "query-lang"
version = "0.1.0"
edition = "2021"

[lib]
name = "query_lang"
crate-type = ["cdylib", "rlib"]

[dependencies]
pest = "2.7.15"
pest_derive = "2.7.15"

[dependencies.pyo3]
version = "0.23.4"
features = ["extension-module"]
