[project]
name = "parsing_benchmark"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
  "mypy>=1.15.0",
  "rich>=13.9.4",
  "rust_pest",
]

[tool.uv.sources]
rust_pest = { workspace = true }

[tool.uv.workspace]
members = ["rust_pest"]
