
start: expr
expr: and_expr | or_expr | comparison

and_expr_or_comparision: and_expr | bracket_expr
or_expr_or_comparision: or_expr | bracket_expr

and_expr: bracket_expr "and" and_expr_or_comparision
or_expr: bracket_expr "or" or_expr_or_comparision

bracket_expr: "(" expr ")" | comparison
comparison: FIELD OP ESCAPED_STRING

WHITESPACE: " " | "\t" | "\n" | "\r"
FIELD: /\w+/
OP: "!=" | "=~" | "!~" | "="

%import common.ESCAPED_STRING

%ignore WHITESPACE
